import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
// Imported rather than fully qualified: inside a build script `java` resolves to the
// JavaPluginExtension accessor, so `java.util.Properties` does not compile.
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

/**
 * The CARTO basemap key, from `local.properties` on a person's own machine or from the
 * environment on CI. Blank when neither supplies one.
 *
 * Not a secret, and not treated as one: both targets are clients, so the key ships inside
 * the artifact and is visible in the browser's network tab on the first tile request.
 * Keeping it out of git stops it leaking into the repo and lets each person use their own
 * quota, which is the whole of what this buys.
 */
val cartoApiKey: Provider<String> = providers.provider {
    val local = rootProject.file("local.properties")
    val fromFile = if (local.isFile) {
        val properties = Properties()
        local.inputStream().use { properties.load(it) }
        properties.getProperty("carto.apiKey")
    } else {
        null
    }
    (fromFile ?: System.getenv("CARTO_API_KEY") ?: "").trim()
}

/**
 * Writes the key into a Kotlin constant the shared code can read.
 *
 * A hand-rolled task rather than BuildKonfig: this project's whole plugin list is four
 * entries, and one generated constant does not justify a fifth.
 */
val generateMapKeys by tasks.registering {
    description = "Generates MapKeys.kt holding the basemap API key."
    val key = cartoApiKey
    val outputDir = layout.buildDirectory.dir("generated/mapkeys")
    // Declared so the task reruns when the key changes and is skipped when it has not.
    inputs.property("cartoApiKey", key)
    outputs.dir(outputDir)
    doLast {
        // A stray quote or backslash in the key would otherwise generate a file that does
        // not compile, and the error would point at generated code rather than at the key.
        val escaped = key.get().replace("\\", "\\\\").replace("\"", "\\\"")
        val file = outputDir.get().file("no/gatelangs/app/map/MapKeys.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package no.gatelangs.app.map

            // Generated by the generateMapKeys Gradle task. Do not edit, do not commit.
            // Blank when no key is configured, which TileSource treats as "no key".
            internal const val CARTO_API_KEY: String = "$escaped"
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    // JDK 21 toolchain (auto-provisioned via foojay): matches the JetBrains Runtime
    // that Compose Hot Reload runs the desktop app on.
    jvmToolchain(21)

    jvm()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain {
            // The task provider, not a bare path: that is what makes every compilation —
            // jvm, wasmJs and both test variants — depend on the generator automatically.
            kotlin.srcDir(generateMapKeys)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // The @Preview annotation, published under the androidx name for all
            // targets (replaces the deprecated compose.components.uiToolingPreview).
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.compose.material.icons.core)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.ktor.client.okhttp)
        }
        wasmJsMain.dependencies {
            implementation(libs.kotlinx.browser)
            implementation(libs.ktor.client.js)
        }
    }
}

compose.resources {
    packageOfResClass = "no.gatelangs.app.resources"
}

compose.desktop {
    application {
        mainClass = "no.gatelangs.app.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Gatelangs"
            packageVersion = "1.0.0"
        }
    }
}
